### ISSUE TITLE
Warnings on console

### ISSUE THREAD

**Issue by senerdude** [govuk-react/govuk-react#713] opened 2020-02-07 11:43 UTC
I'm having below warnings caused by components. Is there any plan to update these components?

(created by LinkAnchor)
index.js:1375 Warning: React does not recognize the `noVisitedState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `novisitedstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

(created by LinkAnchor)
index.js:1375 Warning: React does not recognize the `textColour` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textcolour` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

(created by styled.input) - (created by TopNav)
index.js:1375 Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

**Comment by Loque-** [comment] 2020-02-07 12:03
The project is open source so the idea is that anyone can submit a PR (there are people here that can review and push releases).

I haven't seen the issue personally so if you have the capacity to throw a codesandbox together to demonstrate the issue that would be awesome (and would help someone address the warnings).

**Comment by penx** [comment] 2020-02-07 12:07
Pretty sure the first two are due to styled-components/styled-components#439

Codesandbox for the 3rd issue appreciated.

No there are no plans to address this, but as @Loque- says, we would encourage contributions.

**Comment by penx** [comment] 2020-02-07 12:09
We provided a fix for this in styled-components but it was rejected, and unfortunately they don't yet have a plan to fix it.

https://github.com/styled-components/styled-components/pull/2392#issuecomment-464496745

**Comment by senerdude** [comment] 2020-02-07 12:17
Thanks, I'll work on it soon as when I have time then.

**Comment by penx** [comment] 2021-05-14 18:45
This can now be addressed via https://github.com/styled-components/styled-components/pull/3006

**Comment by penx** [comment] 2021-05-15 15:11
possible duplicate of #652

**Closed** 2021-05-15 22:34 UTC
