### ISSUE TITLE
Wrapping styled components in a regular component can cause styling issues

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#527] opened 2019-02-02 15:28 UTC
Components are typically defined as a styled component, and then wrapped in a regular component.  This is done because react-docgen does not document components that are only styled components.

Unfortunately this method can cause problems for styling rules with descendent selectors, and also increases the complexity of components.

An alternate approach is this:
```jsx
const Component = styled('div')({
  color: 'purple',
});

const DocumentedComponent = props => <StyledComponent {...props} />;

DocumentedComponent.defaultProps = { propName: 'value' };
DocumentedComponent.propTypes = { propName: PropTypes.type };

Component.defaultProps = DocumentedComponent.defaultProps;
Component.propTypes = DocumentedComponent.propTypes;

// Named export so react-docgen will generate docs
export { DocumentedComponent };
// Export un-wrapped styled component
export default Component;
```

Adopting this approach means that react-docgen can still generate documentation, but the un-wrapped component will be the one that's used, allowing styling based on descendent selectors to work correctly and reliably.

**Comment by stevesims** [comment] 2019-02-02 15:39
This issue is strongly related to #81

**Comment by stevesims** [comment] 2019-02-04 11:59
The slight down-side to this approach is that the `DocumentedComponent` will not get test coverage - unless a unit test is explicitly written to use it.

**Comment by penx** [comment] 2021-05-16 15:05
> Components are typically defined as a styled component, and then wrapped in a regular component

can you provide an example?

> This is done because react-docgen does not document components that are only styled components.

My understanding is this is done via

```js
const Caption = props => <StyledCaption {...props} />;
```

is that what you mean?

> Unfortunately this method can cause problems for styling rules with descendent selectors

this doesn't result in an additional dom node so it shouldn't...

**Comment by stevesims** [comment] 2021-05-16 15:11
my memory is hazy on this to be honest

I think the issues were more around if you re-style a component, doing
```jsx
const RestyledCaption = styled(Caption)({ color: 'red' });
```

as noted this was affecting things with descendent selectors, and that was more to do with the resultant class names that styled-components generates than the presence (or lack) of any additional DOM nodes

**Comment by penx** [comment] 2021-05-22 11:43
As there's no known bugs, I'll close this as a duplicate of #81

**Closed by penx** 2021-05-22 11:43 UTC
Labels: documentation, enhancement
